export type GrassCategory =
  | "decorativa"
  | "deportiva"
  | "accesorios"
  | "paisajismo-verde"
  | "paisajismo-colores"
  | "curly"
  | "tenis"
  | "golf"
  | "tapicesped"
  | "futbol";
export type GrassUse =
  | "jardines"
  | "terrazas"
  | "balcones"
  | "pet-friendly"
  | "zonas-infantiles"
  | "deportiva"
  | "muros-verdes"
  | "general";

export interface GrassProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  category: GrassCategory;
  uses: GrassUse[];
  pricePerM2: number;
  fiberHeight: string;
  density: string;
  toneColor: string;
  availableHeights: string[];
  availableColors: string[];
  guarantee: string;
  badge?: string;
  badgeType?: "green" | "amber" | "stone";
  petFriendly: boolean;
  childFriendly: boolean;
  sportSuitable: boolean;
  benefits: string[];
  images: string[];
  available: boolean;
  featured: boolean;
}

export interface Project {
  id: string;
  title: string;
  slug: string;
  description: string;
  category: string;
  location: string;
  metersInstalled: number;
  grassUsed: string;
  grassColor: string;
  installationTime: string;
  warranty: string;
  benefits: string[];
  beforeImages: string[];
  afterImages: string[];
  tags: string[];
}

export interface Testimonial {
  id: string;
  name: string;
  location: string;
  rating: number;
  text: string;
  projectType: string;
}

export const WHATSAPP_NUMBER = "573208523041";

export const INSTALLATION_PRICE_PER_M2 = 15000;

export const products: GrassProduct[] = [
  {
    id: "1",
    name: "Tapicésped",
    slug: "tapicesped",
    description:
      "Grama sintética decorativa de fibra corta, ideal para cubrir superficies con un acabado limpio y uniforme. Perfecta para interiores, exhibidores comerciales y zonas de bajo tráfico.",
    shortDescription:
      "Grama de fibra corta para cubrir superficies con acabado limpio.",
    category: "decorativa",
    uses: ["jardines", "general"],
    pricePerM2: 42000,
    fiberHeight: "11 mm",
    density: "Media",
    toneColor: "Verde uniforme",
    availableHeights: ["11 mm"],
    availableColors: ["Verde"],
    guarantee: "6 meses",
    badge: "Económica",
    badgeType: "stone",
    petFriendly: false,
    childFriendly: true,
    sportSuitable: false,
    benefits: [
      "Fácil instalación",
      "Bajo costo",
      "Acabado uniforme",
      "Liviana y manejable",
    ],
    images: [
      "/productos/grama tapicesped/grama tapicesped (1).jpeg",
      "/productos/grama tapicesped/grama tapicesped (2).jpeg",
      "/productos/grama tapicesped/grama tapicesped (3).jpeg",
      "/productos/grama tapicesped/grama tapicesped (4).jpeg",
    ],
    available: true,
    featured: false,
  },
  {
    id: "2",
    name: "Grama Paisajismo",
    slug: "paisajismo",
    description:
      "Grama sintética de alta calidad para jardines, patios y terrazas residenciales. Sus fibras naturales en diferentes tonos dan una apariencia realista y atractiva. Ideal para transformar espacios exteriores.",
    shortDescription:
      "Grama premium para jardines y terrazas con apariencia ultra-realista.",
    category: "decorativa",
    uses: ["jardines", "terrazas", "balcones"],
    pricePerM2: 52000,
    fiberHeight: "20 - 55 mm",
    density: "Alta",
    toneColor: "Verde bicolor natural",
    availableHeights: ["20 mm", "30 mm", "40 mm", "55 mm"],
    availableColors: ["Verde natural", "Verde oscuro"],
    guarantee: "3 años",
    badge: "Más vendida",
    badgeType: "green",
    petFriendly: true,
    childFriendly: true,
    sportSuitable: false,
    benefits: [
      "Apariencia 100% natural",
      "Drenaje eficiente",
      "Resistente al sol",
      "Fácil mantenimiento",
    ],
    images: [
      "/productos/grama paisajismo/grama paisajimo.jpeg",
      "/productos/grama paisajismo/WhatsApp Image 2026-06-12 at 8.23.37 AM.jpeg",
      "/productos/grama paisajismo/WhatsApp Image 2026-06-12 at 8.23.37 AM (1).jpeg",
      "/productos/grama paisajismo/WhatsApp Image 2026-06-12 at 8.23.37 AM (2).jpeg",
      "/productos/grama paisajismo/WhatsApp Image 2026-06-12 at 8.23.37 AM (3).jpeg",
    ],
    available: true,
    featured: true,
  },
  {
    id: "3",
    name: "Grama Curly",
    slug: "curly",
    description:
      "Grama sintética rizada de diseño moderno disponible en múltiples colores. Perfecta para decoración de interiores, eventos, stands comerciales y proyectos creativos que requieren un toque diferente.",
    shortDescription:
      "Grama rizada decorativa en 8 colores para proyectos creativos.",
    category: "decorativa",
    uses: ["balcones", "terrazas", "general"],
    pricePerM2: 50000,
    fiberHeight: "20 mm",
    density: "Alta",
    toneColor: "Multicolor",
    availableHeights: ["20 mm"],
    availableColors: [
      "Verde",
      "Azul",
      "Rojo",
      "Amarillo",
      "Naranja",
      "Morado",
      "Rosa",
      "Blanco",
    ],
    guarantee: "3 años",
    badge: "Colores",
    badgeType: "amber",
    petFriendly: false,
    childFriendly: true,
    sportSuitable: false,
    benefits: [
      "8 colores disponibles",
      "Diseño único",
      "Ideal para eventos",
      "Resistente al desgaste",
    ],
    images: [
      "/productos/tangara grama curly/tangara grama curly (1).jpeg",
      "/productos/tangara grama curly/tangara grama curly (2).jpeg",
    ],
    available: true,
    featured: true,
  },
  {
    id: "4",
    name: "Grama Tenis",
    slug: "tenis",
    description:
      "Grama sintética especializada para canchas de tenis. Cumple con estándares deportivos internacionales, ofrece rebote uniforme del balón y máxima tracción. Disponible en colores de cancha profesional.",
    shortDescription: "Grama para canchas de tenis con rebote uniforme.",
    category: "deportiva",
    uses: ["deportiva"],
    pricePerM2: 68000,
    fiberHeight: "25 mm",
    density: "Muy alta",
    toneColor: "Verde / Azul / Terracota",
    availableHeights: ["25 mm"],
    availableColors: ["Verde", "Azul", "Terracota", "Gris", "Bordo", "Naranja"],
    guarantee: "3 años",
    badge: "Deportiva",
    badgeType: "stone",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: [
      "Estándar internacional",
      "Rebote uniforme",
      "Alta tracción",
      "Resistente a UV",
    ],
    images: [
      "/productos/grama tennis/gramatenis (1).jpeg",
      "/productos/grama tennis/gramatenis (2).jpeg",
      "/productos/grama tennis/gramatenis (3).jpeg",
      "/productos/grama tennis/gramatenis (4).jpeg",
      "/productos/grama tennis/gramatenis (5).jpeg",
      "/productos/grama tennis/gramatenis (6).jpeg",
    ],
    available: true,
    featured: false,
  },
  {
    id: "5",
    name: "Grama Fútbol",
    slug: "futbol",
    description:
      "Grama sintética de alta performance para canchas de fútbol. Fibra larga y resistente que simula césped natural, con sistema de drenaje integrado y soporte para relleno de arena o caucho.",
    shortDescription: "Grama de alta performance para canchas de fútbol.",
    category: "deportiva",
    uses: ["deportiva"],
    pricePerM2: 78000,
    fiberHeight: "50 mm",
    density: "Muy alta",
    toneColor: "Verde FIFA",
    availableHeights: ["50 mm"],
    availableColors: ["Verde FIFA", "Verde Lima"],
    guarantee: "5 años",
    badge: "Premium",
    badgeType: "green",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: [
      "Fibra larga resistente",
      "Drenaje integrado",
      "Compatible con relleno",
      "Garantía 5 años",
    ],
    images: [
      "/productos/tangara grama tennis/tangara grama tennis (1).jpeg",
      "/productos/tangara grama tennis/tangara grama tennis (2).jpeg",
      "/productos/tangara grama tennis/tangara grama tennis (3).jpeg",
      "/productos/tangara grama tennis/tangara grama tennis (4).jpeg",
      "/productos/tangara grama tennis/tangara grama tennis (5).jpeg",
    ],
    available: true,
    featured: true,
  },
  {
    id: "6",
    name: "Grama Pádel",
    slug: "padel",
    description:
      "Grama sintética diseñada específicamente para canchas de pádel. Fibra corta y compacta que garantiza velocidad de juego óptima y adherencia perfecta del calzado deportivo.",
    shortDescription: "Grama especializada para canchas de pádel.",
    category: "deportiva",
    uses: ["deportiva"],
    pricePerM2: 65000,
    fiberHeight: "12 mm",
    density: "Muy alta",
    toneColor: "Azul / Blanco",
    availableHeights: ["12 mm"],
    availableColors: ["Azul", "Blanco", "Verde"],
    guarantee: "3 años",
    badge: "Deportiva",
    badgeType: "stone",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: [
      "Velocidad óptima de juego",
      "Alta adherencia",
      "Resistente al desgaste",
      "Fácil limpieza",
    ],
    images: [
      "/productos/grama tennis/gramatenis (4).jpeg",
      "/productos/grama tennis/gramatenis (5).jpeg",
      "/productos/grama tennis/gramatenis (6).jpeg",
    ],
    available: true,
    featured: false,
  },
  {
    id: "7",
    name: "Bandeja para Mascotas",
    slug: "bandeja-mascotas",
    description:
      "Sistema de bandeja con grama sintética pet friendly diseñado para mascotas en apartamentos y espacios sin jardín. Drenaje eficiente, fácil limpieza y materiales 100% seguros para animales.",
    shortDescription:
      "Sistema de baño para mascotas con grama sintética y drenaje.",
    category: "accesorios",
    uses: ["pet-friendly"],
    pricePerM2: 35000,
    fiberHeight: "Estándar",
    density: "Media",
    toneColor: "Verde",
    availableHeights: ["Estándar"],
    availableColors: ["Verde"],
    guarantee: "1 año",
    badge: "Pet Friendly",
    badgeType: "green",
    petFriendly: true,
    childFriendly: false,
    sportSuitable: false,
    benefits: [
      "100% seguro para mascotas",
      "Drenaje eficiente",
      "Fácil de limpiar",
      "Libre de tóxicos",
    ],
    images: [
      "/productos/bandeja para perros/918b4fa3-509c-4021-89b9-f3f0b3a39812.png",
      "/productos/bandeja para perros/c0a98667-3822-47ac-8b0e-b32226fcc64a.png",
    ],
    available: true,
    featured: true,
  },
  {
    id: "8",
    name: "Paisajismo 20mm Liviana (Basic o Essence) RE",
    slug: "paisajismo-20mm-liviana-basic-o-essence-re",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 49000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["20mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "9",
    name: "Paisajismo 20mm Tráfico Normal CCG",
    slug: "paisajismo-20mm-trafico-normal-ccg",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 56000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["20mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: ["/productos/grama paisajismo/Paisajismo 20 mm Trafico NORMAL CCG..jpeg"],
    available: true,
    featured: false,
  },
  {
    id: "10",
    name: "Paisajismo 20mm Pro Fibra Gruesa FE",
    slug: "paisajismo-20mm-pro-fibra-gruesa-fe",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 59000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["20mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "11",
    name: "Paisajismo 20mm Verde Verde Greener CU",
    slug: "paisajismo-20mm-verde-verde-greener-cu",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 62000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["20mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "12",
    name: "Paisajismo 20mm Verde Lima FE",
    slug: "paisajismo-20mm-verde-lima-fe",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 62000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Verde lima",
    availableHeights: ["20mm"],
    availableColors: ["Verde lima"],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: ["/productos/grama paisajismo/Paisajismo 20mm verde lima FE..jpeg"],
    available: true,
    featured: false,
  },
  {
    id: "13",
    name: "Paisajismo 20mm CU",
    slug: "paisajismo-20mm-cu",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 62000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["20mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: ["/productos/grama paisajismo/Paisajismo 20 mm CU..jpeg"],
    available: true,
    featured: false,
  },
  {
    id: "14",
    name: "Paisajismo 20mm (22mm) CUP",
    slug: "paisajismo-20mm-22mm-cup",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 71000,
    fiberHeight: "22mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["22mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "15",
    name: "Paisajismo 25mm Terrace RE",
    slug: "paisajismo-25mm-terrace-re",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 59000,
    fiberHeight: "25mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["25mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "16",
    name: "Paisajismo 30mm CCG",
    slug: "paisajismo-30mm-ccg",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 59000,
    fiberHeight: "30mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["30mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "17",
    name: "Paisajismo 30mm Vita RE",
    slug: "paisajismo-30mm-vita-re",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 62000,
    fiberHeight: "30mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["30mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "18",
    name: "Paisajismo 30mm Pesada CU",
    slug: "paisajismo-30mm-pesada-cu",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 94000,
    fiberHeight: "30mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["30mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "19",
    name: "Paisajismo 40mm CCG",
    slug: "paisajismo-40mm-ccg",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 65000,
    fiberHeight: "40mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["40mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "20",
    name: "Paisajismo 40mm Pesada Trevi RE",
    slug: "paisajismo-40mm-pesada-trevi-re",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 80000,
    fiberHeight: "40mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["40mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "21",
    name: "Paisajismo 55mm RE",
    slug: "paisajismo-55mm-re",
    description:
      "Grama sintética de paisajismo con apariencia natural, ideal para jardines, zonas verdes y áreas de tránsito peatonal moderado. Fibra resistente a rayos UV y de fácil mantenimiento.",
    shortDescription:
      "Grama de paisajismo con apariencia natural para jardines y zonas verdes.",
    category: "paisajismo-verde",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 110000,
    fiberHeight: "55mm",
    density: "Alta",
    toneColor: "Verde",
    availableHeights: ["55mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Apariencia natural", "Resistente a rayos UV", "Fácil mantenimiento", "Ideal para tránsito peatonal"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "22",
    name: "Paisajismo 20mm Liviana Summer (rojo, negro, azul) RE",
    slug: "paisajismo-20mm-liviana-summer-re",
    description:
      "Grama sintética decorativa en colores vivos, perfecta para paisajismo creativo, zonas infantiles y espacios que buscan un toque distintivo.",
    shortDescription:
      "Grama decorativa en colores vivos para paisajismo creativo.",
    category: "paisajismo-colores",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 49000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Multicolor",
    availableHeights: ["20mm"],
    availableColors: ["Rojo", "Negro", "Azul"],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Colores vibrantes y duraderos", "Resistente a rayos UV", "Ideal para espacios creativos", "Fácil instalacion"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "23",
    name: "Paisajismo 20mm Colors (fucsia, amarillo mostaza) CU",
    slug: "paisajismo-20mm-colors-fucsia-amarillo-mostaza-cu",
    description:
      "Grama sintética decorativa en colores vivos, perfecta para paisajismo creativo, zonas infantiles y espacios que buscan un toque distintivo.",
    shortDescription:
      "Grama decorativa en colores vivos para paisajismo creativo.",
    category: "paisajismo-colores",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 59000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Multicolor",
    availableHeights: ["20mm"],
    availableColors: ["Fucsia", "Amarillo mostaza"],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Colores vibrantes y duraderos", "Resistente a rayos UV", "Ideal para espacios creativos", "Fácil instalacion"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "24",
    name: "Paisajismo 20mm Colores (azul, rojo, amarillo, morado, blanco) HEC CCG",
    slug: "paisajismo-20mm-colores-hec-ccg",
    description:
      "Grama sintética decorativa en colores vivos, perfecta para paisajismo creativo, zonas infantiles y espacios que buscan un toque distintivo.",
    shortDescription:
      "Grama decorativa en colores vivos para paisajismo creativo.",
    category: "paisajismo-colores",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 59000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Multicolor",
    availableHeights: ["20mm"],
    availableColors: ["Azul", "Rojo", "Amarillo", "Morado", "Blanco"],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Colores vibrantes y duraderos", "Resistente a rayos UV", "Ideal para espacios creativos", "Fácil instalacion"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "25",
    name: "Paisajismo 20mm Colores (13 tonos) FE",
    slug: "paisajismo-20mm-colores-13-tonos-fe",
    description:
      "Grama sintética decorativa en colores vivos, perfecta para paisajismo creativo, zonas infantiles y espacios que buscan un toque distintivo.",
    shortDescription:
      "Grama decorativa en colores vivos para paisajismo creativo.",
    category: "paisajismo-colores",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 62000,
    fiberHeight: "20mm",
    density: "Alta",
    toneColor: "Multicolor",
    availableHeights: ["20mm"],
    availableColors: [
      "Azul",
      "Azul claro",
      "Rojo",
      "Amarillo",
      "Terracota",
      "Naranja",
      "Lila",
      "Verde lima",
      "Negro",
      "Camel",
      "Fucsia",
      "Gris",
      "Blanco",
    ],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Colores vibrantes y duraderos", "Resistente a rayos UV", "Ideal para espacios creativos", "Fácil instalacion"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "26",
    name: "Curly 14mm 750gr CU",
    slug: "curly-14mm-750gr-cu",
    description:
      "Grama sintética rizada de diseño moderno, ideal para decoracion de interiores, stands comerciales y proyectos creativos.",
    shortDescription:
      "Grama rizada decorativa para proyectos creativos.",
    category: "curly",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 62000,
    fiberHeight: "14mm",
    density: "750 gr",
    toneColor: "Verde",
    availableHeights: ["14mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Diseño rizado unico", "Ideal para decoracion interior", "Resistente al desgaste", "Fácil de limpiar"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "27",
    name: "Curly 14mm 900gr CU",
    slug: "curly-14mm-900gr-cu",
    description:
      "Grama sintética rizada de diseño moderno, ideal para decoracion de interiores, stands comerciales y proyectos creativos.",
    shortDescription:
      "Grama rizada decorativa para proyectos creativos.",
    category: "curly",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 78000,
    fiberHeight: "14mm",
    density: "900 gr",
    toneColor: "Verde",
    availableHeights: ["14mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Diseño rizado unico", "Ideal para decoracion interior", "Resistente al desgaste", "Fácil de limpiar"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "28",
    name: "Tenis 20mm Verde (New Deluxe) CUP",
    slug: "tenis-20mm-verde-new-deluxe-cup",
    description:
      "Grama sintética especializada para canchas de tenis y pádel, con rebote uniforme del balón y alta resistencia al tráfico deportivo intenso.",
    shortDescription:
      "Grama deportiva para canchas de tenis y pádel.",
    category: "tenis",
    uses: ["deportiva"],
    pricePerM2: 53000,
    fiberHeight: "20mm",
    density: "Muy alta",
    toneColor: "Verde",
    availableHeights: ["20mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Rebote uniforme", "Alta resistencia al tráfico", "Estándar deportivo", "Resistente a UV"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "29",
    name: "Tenis 25mm Verde (New Deluxe) CUP",
    slug: "tenis-25mm-verde-new-deluxe-cup",
    description:
      "Grama sintética especializada para canchas de tenis y pádel, con rebote uniforme del balón y alta resistencia al tráfico deportivo intenso.",
    shortDescription:
      "Grama deportiva para canchas de tenis y pádel.",
    category: "tenis",
    uses: ["deportiva"],
    pricePerM2: 62000,
    fiberHeight: "25mm",
    density: "Muy alta",
    toneColor: "Verde",
    availableHeights: ["25mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Rebote uniforme", "Alta resistencia al tráfico", "Estándar deportivo", "Resistente a UV"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "30",
    name: "Tenis 20mm Colores (naranja, azul oscuro, amarillo) TAISH",
    slug: "tenis-20mm-colores-taish",
    description:
      "Grama sintética especializada para canchas de tenis y pádel, con rebote uniforme del balón y alta resistencia al tráfico deportivo intenso.",
    shortDescription:
      "Grama deportiva para canchas de tenis y pádel.",
    category: "tenis",
    uses: ["deportiva"],
    pricePerM2: 67000,
    fiberHeight: "20mm",
    density: "Muy alta",
    toneColor: "Multicolor",
    availableHeights: ["20mm"],
    availableColors: ["Naranja", "Azul oscuro", "Amarillo"],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Rebote uniforme", "Alta resistencia al tráfico", "Estándar deportivo", "Resistente a UV"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "31",
    name: "Tenis 22mm Colores MUNDIG",
    slug: "tenis-22mm-colores-mundig",
    description:
      "Grama sintética especializada para canchas de tenis y pádel, con rebote uniforme del balón y alta resistencia al tráfico deportivo intenso.",
    shortDescription:
      "Grama deportiva para canchas de tenis y pádel.",
    category: "tenis",
    uses: ["deportiva"],
    pricePerM2: 67000,
    fiberHeight: "22mm",
    density: "Muy alta",
    toneColor: "Multicolor",
    availableHeights: ["22mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Rebote uniforme", "Alta resistencia al tráfico", "Estándar deportivo", "Resistente a UV"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "32",
    name: "Tenis o Pádel Fibrilada 14mm (azul y blanco) HEC CCGR",
    slug: "tenis-padel-fibrilada-14mm-hec-ccgr",
    description:
      "Grama sintética especializada para canchas de tenis y pádel, con rebote uniforme del balón y alta resistencia al tráfico deportivo intenso.",
    shortDescription:
      "Grama deportiva para canchas de tenis y pádel.",
    category: "tenis",
    uses: ["deportiva"],
    pricePerM2: 78000,
    fiberHeight: "14mm",
    density: "Muy alta",
    toneColor: "Multicolor",
    availableHeights: ["14mm"],
    availableColors: ["Azul", "Blanco"],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Rebote uniforme", "Alta resistencia al tráfico", "Estándar deportivo", "Resistente a UV"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "33",
    name: "Golf Fibrilada 12mm CASA",
    slug: "golf-fibrilada-12mm-casa",
    description:
      "Grama sintética para campos y zonas de práctica de golf, con fibra rizada o fibrilada que ofrece un rodamiento de bola preciso y consistente.",
    shortDescription:
      "Grama deportiva para campos y zonas de práctica de golf.",
    category: "golf",
    uses: ["deportiva"],
    pricePerM2: 89000,
    fiberHeight: "12mm",
    density: "Muy alta",
    toneColor: "Verde",
    availableHeights: ["12mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Rodamiento de bola preciso", "Superficie uniforme", "Alta durabilidad", "Bajo mantenimiento"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "34",
    name: "Golf Curly HEC CCG",
    slug: "golf-curly-hec-ccg",
    description:
      "Grama sintética para campos y zonas de práctica de golf, con fibra rizada o fibrilada que ofrece un rodamiento de bola preciso y consistente.",
    shortDescription:
      "Grama deportiva para campos y zonas de práctica de golf.",
    category: "golf",
    uses: ["deportiva"],
    pricePerM2: 96000,
    fiberHeight: "14mm",
    density: "Muy alta",
    toneColor: "Verde",
    availableHeights: ["14mm"],
    availableColors: [],
    guarantee: "3 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Rodamiento de bola preciso", "Superficie uniforme", "Alta durabilidad", "Bajo mantenimiento"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "35",
    name: "Tapicesped 10mm HEC CCG",
    slug: "tapicesped-10mm-hec-ccg",
    description:
      "Grama sintética de fibra corta tipo tapicesped, ideal para cubrir superficies con un acabado limpio y uniforme en interiores y exteriores de bajo tráfico.",
    shortDescription:
      "Grama de fibra corta para acabados limpios y uniformes.",
    category: "tapicesped",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 34000,
    fiberHeight: "10mm",
    density: "Media",
    toneColor: "Verde",
    availableHeights: ["10mm"],
    availableColors: [],
    guarantee: "6 meses",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Fácil instalacion", "Acabado uniforme", "Bajo costo", "Liviana y manejable"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "36",
    name: "Tapicesped 10mm FE",
    slug: "tapicesped-10mm-fe",
    description:
      "Grama sintética de fibra corta tipo tapicesped, ideal para cubrir superficies con un acabado limpio y uniforme en interiores y exteriores de bajo tráfico.",
    shortDescription:
      "Grama de fibra corta para acabados limpios y uniformes.",
    category: "tapicesped",
    uses: ["jardines", "terrazas", "general"],
    pricePerM2: 34000,
    fiberHeight: "10mm",
    density: "Media",
    toneColor: "Verde",
    availableHeights: ["10mm"],
    availableColors: [],
    guarantee: "6 meses",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: false,
    benefits: ["Fácil instalacion", "Acabado uniforme", "Bajo costo", "Liviana y manejable"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "37",
    name: "Futbol 50mm Verde CCG",
    slug: "futbol-50mm-verde-ccg",
    description:
      "Grama sintética de alta performance para canchas de futbol, con fibra larga y resistente que simula césped natural y soporta uso intensivo.",
    shortDescription:
      "Grama de alta performance para canchas de futbol.",
    category: "futbol",
    uses: ["deportiva"],
    pricePerM2: 55000,
    fiberHeight: "50mm",
    density: "Muy alta",
    toneColor: "Verde",
    availableHeights: ["50mm"],
    availableColors: [],
    guarantee: "5 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Alta resistencia al desgaste", "Simula césped natural", "Soporta relleno de arena/caucho", "Ideal para uso intensivo"],
    images: [],
    available: true,
    featured: false,
  },
  {
    id: "38",
    name: "Futbol 50mm (amarilla y blanca) CCG",
    slug: "futbol-50mm-amarilla-blanca-ccg",
    description:
      "Grama sintética de alta performance para canchas de futbol, con fibra larga y resistente que simula césped natural y soporta uso intensivo.",
    shortDescription:
      "Grama de alta performance para canchas de futbol.",
    category: "futbol",
    uses: ["deportiva"],
    pricePerM2: 62000,
    fiberHeight: "50mm",
    density: "Muy alta",
    toneColor: "Multicolor",
    availableHeights: ["50mm"],
    availableColors: ["Amarillo", "Blanco"],
    guarantee: "5 años",
    petFriendly: false,
    childFriendly: false,
    sportSuitable: true,
    benefits: ["Alta resistencia al desgaste", "Simula césped natural", "Soporta relleno de arena/caucho", "Ideal para uso intensivo"],
    images: [],
    available: true,
    featured: false,
  },
];

export const projects: Project[] = [
  {
    id: "1",
    title: "Acceso vehicular y andén en vivienda de lujo",
    slug: "acceso-vehicular-anden-vivienda-lujo",
    description:
      "Franjas de grama sintética embebidas en el adoquinado de concreto del acceso vehicular y el andén de una vivienda moderna, dando continuidad visual entre la fachada y la calle sin sacrificar la circulación de vehículos.",
    category: "Residencial",
    location: "Bucaramanga, Santander",
    metersInstalled: 70,
    grassUsed: "Grama Paisajismo 20mm",
    grassColor: "Verde natural bicolor",
    installationTime: "3 días",
    warranty: "3 años",
    benefits: [
      "Integración total entre la fachada y el andén, sin cortes visibles",
      "Cero mantenimiento en una zona de alto tránsito peatonal y vehicular",
      "Drenaje eficiente que evita encharcamientos en el adoquinado",
    ],
    beforeImages: [],
    afterImages: [
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.28_AM.jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.28_AM_(1).jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.31_AM.jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.32_AM.jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.32_AM_(1).jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.32_AM_(2).jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.33_AM.jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_10.57.34_AM.jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_11.00.06_AM.jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_11.00.06_AM_(1).jpeg",
      "/proyectos/luxury/WhatsApp_Image_2025-03-15_at_11.00.06_AM_(2).jpeg",
    ],
    tags: ["fachada", "acceso vehicular", "decorativo", "residencial"],
  },
  {
    id: "2",
    title: "Cancha de fútbol 7 al aire libre",
    slug: "cancha-futbol-7-aire-libre",
    description:
      "Cancha de fútbol 7 con grama de alto tráfico, líneas de juego marcadas, portería reglamentaria y cerramiento perimetral con malla, lista para uso intensivo.",
    category: "Deportivo",
    location: "Piedecuesta, Santander",
    metersInstalled: 450,
    grassUsed: "Grama Fútbol 50mm",
    grassColor: "Verde FIFA",
    installationTime: "6 días",
    warranty: "5 años",
    benefits: [
      "Superficie de juego uniforme, apta para uso intensivo",
      "Menor riesgo de lesiones gracias al amortiguamiento de la fibra",
      "Cero riego ni corte de césped en una cancha de 450 m²",
    ],
    beforeImages: [],
    afterImages: [
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_10.59.37_AM.jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_10.59.37_AM_(1).jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_10.59.37_AM_(2).jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_10.59.38_AM.jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_10.59.38_AM_(1).jpeg",
    ],
    tags: ["deportivo", "fútbol", "cancha", "club"],
  },
  {
    id: "3",
    title: "Zona de juegos infantil en cubierta de edificio",
    slug: "zona-juegos-infantil-cubierta-edificio",
    description:
      "Parque infantil en la cubierta de un edificio con juegos en madera (rodadero, trepadora, túnel) sobre grama de alto amortiguamiento, con zonas de seguridad en rojo y amarillo bajo cada juego.",
    category: "Infantil",
    location: "Bogotá, Cundinamarca",
    metersInstalled: 90,
    grassUsed: "Grama Paisajismo 30mm",
    grassColor: "Verde con círculos de seguridad rojo y amarillo",
    installationTime: "4 días",
    warranty: "3 años",
    benefits: [
      "Superficie segura y acolchada bajo cada juego",
      "Aprovechamiento de una cubierta que antes no tenía uso",
      "Resistente a la exposición solar y a la lluvia propia de una azotea",
    ],
    beforeImages: [],
    afterImages: [
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.46_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.46_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.47_PM.jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.47_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.47_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.47_PM_(4).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.47_PM_(5).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.48_PM.jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.48_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.48_PM_(2).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.48_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.49_PM.jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.49_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.49_PM_(2).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.49_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.50_PM.jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.50_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.50_PM_(2).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.50_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.50_PM_(4).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.51_PM.jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_5.41.51_PM_(1).jpeg",
    ],
    tags: ["infantil", "zonas-juego", "edificio", "seguridad"],
  },
  {
    id: "4",
    title: "Putting green en terraza residencial",
    slug: "putting-green-terraza-residencial",
    description:
      "Green de práctica de golf instalado en la terraza de un edificio residencial, con hoyos, banderines reglamentarios y superficie de rodadura uniforme para putt.",
    category: "Deportivo",
    location: "Medellín, Antioquia",
    metersInstalled: 45,
    grassUsed: "Golf Fibrilada 12mm",
    grassColor: "Verde golf",
    installationTime: "2 días",
    warranty: "3 años",
    benefits: [
      "Rodamiento de bola preciso y consistente para practicar putt",
      "Espacio deportivo funcional dentro de una terraza residencial",
      "Sin riego ni corte para mantener el green siempre listo",
    ],
    beforeImages: [],
    afterImages: [
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_11.05.44_AM.jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_11.05.44_AM_(1).jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_11.05.45_AM.jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_11.05.45_AM_(1).jpeg",
    ],
    tags: ["golf", "putting-green", "terraza", "edificio"],
  },
  {
    id: "5",
    title: "Zona verde de parque con rayuela",
    slug: "zona-verde-parque-rayuela",
    description:
      "Recuperación de zona verde en un parque público con grama de colores y un juego de rayuela numerado, junto al área de juegos infantiles existente.",
    category: "Infantil",
    location: "Cali, Valle del Cauca",
    metersInstalled: 110,
    grassUsed: "Grama Paisajismo Colores",
    grassColor: "Multicolor sobre verde",
    installationTime: "3 días",
    warranty: "3 años",
    benefits: [
      "Recuperación de una zona verde deteriorada del parque",
      "Espacio de juego educativo y seguro para los niños del sector",
      "Colores resistentes a la intemperie y al uso constante",
    ],
    beforeImages: [],
    afterImages: [
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.23_PM_(2).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.24_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.24_PM_(2).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.24_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.25_PM.jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.25_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.25_PM_(2).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.25_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.25_PM_(4).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.26_PM.jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.26_PM_(1).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.26_PM_(2).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.26_PM_(3).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.26_PM_(4).jpeg",
      "/proyectos/parques/WhatsApp_Image_2025-03-15_at_6.07.27_PM.jpeg",
    ],
    tags: ["infantil", "parque público", "rayuela", "colores"],
  },
  {
    id: "6",
    title: "Terraza rooftop con jardineras",
    slug: "terraza-rooftop-jardineras",
    description:
      "Cubrimiento total de una terraza en azotea con vista a la ciudad, combinando grama decorativa con jardineras de plantas trepadoras y flores.",
    category: "Residencial",
    location: "Bucaramanga, Santander",
    metersInstalled: 55,
    grassUsed: "Grama Paisajismo 30mm",
    grassColor: "Verde natural",
    installationTime: "2 días",
    warranty: "3 años",
    benefits: [
      "Aprovechamiento total de la azotea como zona social",
      "Combinación de grama y jardineras para un ambiente natural",
      "Superficie fresca y cómoda para caminar descalzo",
    ],
    beforeImages: [],
    afterImages: [
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_5.41.43_PM.jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_5.41.43_PM_(1).jpeg",
    ],
    tags: ["terraza", "rooftop", "jardineras", "decorativo"],
  },
  {
    id: "7",
    title: "Piso deportivo en zona funcional de gimnasio",
    slug: "piso-deportivo-zona-funcional-gimnasio",
    description:
      "Instalación de grama sintética en la zona de entrenamiento funcional de un gimnasio, combinada con piso de caucho para ejercicios de arrastre, core y movilidad.",
    category: "Comercial",
    location: "Bogotá, Cundinamarca",
    metersInstalled: 80,
    grassUsed: "Tapicésped deportivo",
    grassColor: "Verde",
    installationTime: "1 día",
    warranty: "6 meses",
    benefits: [
      "Superficie amortiguada para ejercicios de alto impacto",
      "Diferenciación visual clara entre la zona funcional y la de pesas",
      "Fácil limpieza en un espacio de uso constante",
    ],
    beforeImages: [],
    afterImages: [
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_10.57.28_AM_(2).jpeg",
      "/proyectos/sports/WhatsApp_Image_2025-03-15_at_10.58.24_AM.jpeg",
    ],
    tags: ["comercial", "gimnasio", "entrenamiento funcional"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "María González",
    location: "Bucaramanga",
    rating: 5,
    text: "Quedé encantada con el resultado. La grama se ve completamente natural y la instalación fue impecable. El equipo fue muy profesional.",
    projectType: "Jardín residencial",
  },
  {
    id: "2",
    name: "Carlos Mendoza",
    location: "Bogotá",
    rating: 5,
    text: "Transformaron mi terraza por completo. El proceso fue rápido y el acabado es premium. Mis vecinos me preguntan dónde la conseguí.",
    projectType: "Terraza apartamento",
  },
  {
    id: "3",
    name: "Laura Jiménez",
    location: "Medellín",
    rating: 5,
    text: "La grama para la zona de juegos de mis hijos es perfecta. Segura, fácil de limpiar y se ve hermosa. 100% recomendada.",
    projectType: "Zona infantil",
  },
  {
    id: "4",
    name: "Andrés Ruiz",
    location: "Cali",
    rating: 4,
    text: "Excelente calidad del producto y muy buen precio. El tiempo de instalación fue el prometido. Muy satisfecho con el resultado.",
    projectType: "Jardín comercial",
  },
];

export const categories = [
  { id: "jardines", label: "Jardines", icon: "🌿", href: "/catalogo?uso=jardines" },
  { id: "terrazas", label: "Terrazas", icon: "🏠", href: "/catalogo?uso=terrazas" },
  { id: "balcones", label: "Balcones", icon: "🌱", href: "/catalogo?uso=balcones" },
  { id: "pet-friendly", label: "Mascotas", icon: "🐕", href: "/catalogo?uso=pet-friendly" },
  { id: "zonas-infantiles", label: "Niños", icon: "🧒", href: "/catalogo?uso=zonas-infantiles" },
  { id: "deportiva", label: "Deportiva", icon: "⚽", href: "/catalogo?uso=deportiva" },
  { id: "muros-verdes", label: "Muros Verdes", icon: "🌲", href: "/catalogo?uso=muros-verdes" },
  { id: "general", label: "Instalación", icon: "🔧", href: "/instalacion" },
] as const;

export const solutions = [
  {
    title: "Quiero renovar mi patio",
    description: "Transforma tu patio con grama sintética de alta calidad que luce natural todo el año.",
    icon: "🏡",
    href: "/catalogo?uso=jardines",
    image: "/proyectos/proyecto-1/despues-1.jpg",
  },
  {
    title: "Terraza más verde",
    description: "Convierte tu terraza o balcón en un oasis verde sin mantenimiento.",
    icon: "🌿",
    href: "/catalogo?uso=terrazas",
    image: "/soluciones/terraza.jpg",
  },
  {
    title: "Zona segura para niños",
    description: "Grama suave, acolchada y sin toxinas para que tus hijos jueguen tranquilos.",
    icon: "🧒",
    href: "/catalogo?uso=zonas-infantiles",
    image: "/soluciones/ninos.jpg",
  },
  {
    title: "Espacio pet friendly",
    description: "Materiales seguros para mascotas con drenaje eficiente y fácil limpieza.",
    icon: "🐕",
    href: "/catalogo?uso=pet-friendly",
    image: "/soluciones/mascotas.png",
  },
  {
    title: "Instalación comercial",
    description: "Proyectos a medida para locales, oficinas, centros comerciales y hoteles.",
    icon: "🏢",
    href: "/contacto",
    image: "/soluciones/comercial.jpg",
  },
  {
    title: "Cancha deportiva",
    description: "Canchas de fútbol, tenis y pádel con grama certificada y garantía de 5 años.",
    icon: "⚽",
    href: "/catalogo?uso=deportiva",
    image: "/soluciones/deportiva.png",
  },
];

export const benefits = [
  { icon: "✅", title: "Instalación profesional", description: "Equipo certificado con años de experiencia." },
  { icon: "🌿", title: "Materiales premium", description: "Grama de alta calidad resistente al sol y lluvia." },
  { icon: "💧", title: "Fácil mantenimiento", description: "Sin cortar, abonar ni regar. Solo limpiar ocasionalmente." },
  { icon: "🐕", title: "Ideal para mascotas", description: "Materiales no tóxicos y drenaje eficiente." },
  { icon: "💦", title: "Drenaje eficiente", description: "Sistema de drenaje integrado que evita encharcamientos." },
  { icon: "🎨", title: "Apariencia natural", description: "Fibras multitonales que imitan el césped real." },
  { icon: "📞", title: "Asesoría personalizada", description: "Te ayudamos a elegir la grama perfecta para tu espacio." },
  { icon: "⚡", title: "Cotización rápida", description: "Recibe tu cotización por WhatsApp en minutos." },
];

export const processSteps = [
  { step: "01", title: "Asesoría inicial", description: "Conversamos sobre tu espacio, necesidades y presupuesto." },
  { step: "02", title: "Medición del área", description: "Calculamos los metros cuadrados exactos para tu proyecto." },
  { step: "03", title: "Selección de grama", description: "Te ayudamos a elegir el tipo ideal según tu uso y gusto." },
  { step: "04", title: "Cotización", description: "Recibes una cotización detallada sin compromisos." },
  { step: "05", title: "Instalación profesional", description: "Nuestro equipo instala en el tiempo acordado." },
  { step: "06", title: "Entrega del espacio", description: "Entregamos tu espacio transformado y garantizado." },
];
